import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useSelector } from 'react-redux'
import { getCheckoutQuote } from '../../services/chatService'
import { Calendar, MapPin, ArrowLeft } from 'lucide-react'

const AIPaymentQuotePage = () => {
  const navigate = useNavigate()
  const { quoteId } = useParams()
  const { isAuthenticated, userType } = useSelector((state) => state.auth)

  const [quote, setQuote] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!quoteId) {
      setError('Missing quote ID')
      setLoading(false)
      return
    }

    const loadQuote = async () => {
      try {
        const data = await getCheckoutQuote(quoteId)
        setQuote(data)
      } catch (err) {
        console.error('Error loading AI checkout quote:', err)
        setError('Unable to load quote. Please try asking the assistant again.')
      } finally {
        setLoading(false)
      }
    }

    loadQuote()
  }, [quoteId])

  if (!isAuthenticated || userType !== 'traveler') {
    // Let the existing ProtectedRoute in App.jsx handle redirects; this is a safety net.
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-gray-700 text-lg">Loading your AI quote...</div>
      </div>
    )
  }

  if (error || !quote) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="max-w-md mx-auto bg-white rounded-xl shadow-md p-6 text-center space-y-4">
          <h2 className="text-xl font-semibold text-gray-900">AI Quote Unavailable</h2>
          <p className="text-gray-600">{error || 'Quote not found.'}</p>
          <button
            onClick={() => navigate('/')}
            className="btn-primary px-6 py-2"
          >
            Back to Home
          </button>
        </div>
      </div>
    )
  }

  const totalPrice = Number(quote.total_price_usd || 0)

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <button
          onClick={() => navigate(-1)}
          className="text-primary-600 hover:text-primary-700 mb-6 flex items-center space-x-2"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back</span>
        </button>

        <h1 className="text-3xl font-bold mb-2">AI Trip Quote</h1>
        <p className="text-gray-600 mb-6">
          This quote is generated by the AI concierge from current deals. Prices may change, so
          consider booking soon if it looks good.
        </p>

        <div className="grid md:grid-cols-3 gap-8">
          <div className="md:col-span-2 space-y-4">
            {/* Flights */}
            {quote.flights && quote.flights.length > 0 && (
              <div className="card">
                <h2 className="text-xl font-semibold mb-3">Flights</h2>
                <div className="space-y-3">
                  {quote.flights.map((flight) => (
                    <div
                      key={flight.id}
                      className="border border-gray-200 rounded-lg p-3 flex flex-col sm:flex-row sm:items-center sm:justify-between"
                    >
                      <div>
                        <div className="flex items-center space-x-2 text-sm text-gray-700 mb-1">
                          <MapPin className="w-4 h-4" />
                          <span>
                            {flight.origin} → {flight.destination}
                          </span>
                        </div>
                        <div className="flex items-center space-x-2 text-xs text-gray-500">
                          <Calendar className="w-3 h-3" />
                          <span>
                            Depart: {new Date(flight.departure_date).toLocaleDateString()}
                            {flight.return_date &&
                              ` · Return: ${new Date(flight.return_date).toLocaleDateString()}`}
                          </span>
                        </div>
                        {flight.airline && (
                          <p className="text-xs text-gray-500 mt-1">Airline: {flight.airline}</p>
                        )}
                      </div>
                      <div className="mt-2 sm:mt-0 text-right">
                        <p className="font-semibold text-primary-600">
                          ${Number(flight.price_usd || 0).toFixed(2)}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Hotels */}
            {quote.hotels && quote.hotels.length > 0 && (
              <div className="card">
                <h2 className="text-xl font-semibold mb-3">Hotels</h2>
                <div className="space-y-3">
                  {quote.hotels.map((hotel) => (
                    <div
                      key={hotel.id}
                      className="border border-gray-200 rounded-lg p-3 flex flex-col sm:flex-row sm:items-center sm:justify-between"
                    >
                      <div>
                        <p className="font-medium text-gray-900">{hotel.hotel_name}</p>
                        <p className="text-sm text-gray-600">{hotel.city}</p>
                        <div className="flex items-center space-x-2 text-xs text-gray-500 mt-1">
                          <Calendar className="w-3 h-3" />
                          <span>
                            {new Date(hotel.check_in_date).toLocaleDateString()} –{' '}
                            {new Date(hotel.check_out_date).toLocaleDateString()}
                          </span>
                        </div>
                      </div>
                      <div className="mt-2 sm:mt-0 text-right">
                        <p className="font-semibold text-primary-600">
                          ${Number(hotel.total_price_usd || 0).toFixed(2)}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="md:col-span-1">
            <div className="card sticky top-4 space-y-3">
              <h2 className="text-xl font-semibold">Quote Summary</h2>
              <div className="flex justify-between text-gray-700">
                <span>Travelers</span>
                <span>{quote.travelers}</span>
              </div>
              {quote.travel_dates && (
                <div className="flex justify-between text-gray-700 text-sm">
                  <span>Dates</span>
                  <span>
                    {quote.travel_dates.departure_date ||
                      quote.travel_dates.check_in}{' '}
                    –{' '}
                    {quote.travel_dates.return_date ||
                      quote.travel_dates.check_out ||
                      ''}
                  </span>
                </div>
              )}
              <div className="border-t pt-3 mt-2">
                <div className="flex justify-between text-lg font-bold">
                  <span>Total</span>
                  <span>${totalPrice.toFixed(2)}</span>
                </div>
              </div>
              <p className="text-xs text-gray-500">
                This is an AI-generated quote for exploration. Final booking and payment will be
                completed in the main checkout flow.
              </p>
              <button
                type="button"
                onClick={() => navigate('/dashboard')}
                className="btn-primary w-full"
              >
                Back to Dashboard
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default AIPaymentQuotePage


